language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage
# command to run tests
script:
  - pytest -m unittest discover -v ./ # command to run unit test
  - coverage run ./test.py # command to run code coverage
after_success:
  - codecov
addons:
  # add our deploy server to known hosts
  # you can set environmental variable in Travis GUI:
  ssh_known_hosts: moon.scs.ryerson.ca 
